name: Docker Image CI Java Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tnemo65/githubaction:latest
    - name: Push the Docker image
      run: |
        docker login -u tnemo65 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push tnemo65/githubaction:latest